name: Convert MD to PDF/HTML
on:
  push:
    branches:
      - main
    paths:
      - 'src/'
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: src
          output_dir: build
          images_dir: src/images
          image_import: ./images
          build_html: true
      - name: Push build
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/*.pdf
          git add src/*.html
          git commit -m "Upload generated files"
          git push
