name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: src
          output_dir: build
          build_html: true
          build_pdf: true
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: src
          path: build
